version: "3"
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - "4004:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./server/db:/docker-entrypoint-initdb.d/:ro
  server:
    build: ./server
    links:
      - db
    ports:
      - "5000:5000"
  client:
    build: ./client
    links:
      - server
    ports:
      - "8080:8080"
