version: "3"
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - "3003:3306"
    volumes:
      - ./server/db:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_ROOT_PASSWORD: root
  client:
    build: ./client
    links:
      - publisher
      - subscriber
    ports:
      - "8080:8080"
    volumes: ["./client:/src"]
    command: ["npm", "run", "serve"]
  publisher:
    build: ./server
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
    volumes: ["./server:/app"]
    restart: unless-stopped
    command: ["flask", "run", "--host=0.0.0.0"]
  broker1:
    build: ./broker
    depends_on:
      - db
    ports:
      - "5005:5005"
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./broker_app.py
    volumes: ["./broker:/broker"]
    restart: unless-stopped
    command: ["flask", "run", "--host=0.0.0.0", "--port=5005"]
  broker2:
    build: ./broker
    depends_on:
      - db
    ports:
      - "5006:5006"
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./broker_app.py
    volumes: ["./broker:/broker"]
    restart: unless-stopped
    command: ["flask", "run", "--host=0.0.0.0", "--port=5006"]
  broker3:
    build: ./broker
    depends_on:
      - db
    ports:
      - "5007:5007"
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./broker_app.py
    volumes: ["./broker:/broker"]
    restart: unless-stopped
    command: ["flask", "run", "--host=0.0.0.0", "--port=5007"]
  broker4:
    build: ./broker
    depends_on:
      - db
    ports:
      - "5008:5008"
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./broker_app.py
    volumes: ["./broker:/broker"]
    restart: unless-stopped
    command: ["flask", "run", "--host=0.0.0.0", "--port=5008"]
  subscriber:
    build: ./subscriber
    depends_on:
      - db
    ports:
      - "5002:5002"
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./sub_app.py
    volumes: ["./subscriber:/subscriber"]
    restart: unless-stopped
    command: ["flask", "run", "--host=0.0.0.0", "--port=5002"]
